# Generated by Django 4.0.1 on 2022-01-15 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saber11', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colegio2020',
            fields=[
                ('colegio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='saber11.colegio')),
            ],
            options={
                'db_table': 'saber2020A',
            },
            bases=('saber11.colegio',),
        ),
    ]
